### PR TITLE
update effects - wrap with return

### PR DESCRIPTION
**Pull request by alex-okrushko**
## Purpose
Update snippets for effects. see discussion at https://github.com/ngrx/platform/issues/2192

## What
the effects callback is now wrapped with return statement

### CODE REVIEW

**Comment by johnpapa** [comment]
@alex-okrushko - thanks for this. I noticed that the action and actions are both replacable with the same value. Is this intentional? Seems they shouldn't be

```
effectName$ = createEffect(() => this.actions$.pipe(
  ofType(action),
  /** An EMPTY observable only emits completion. Replace with your own observable stream */
  operator(() => EMPTY)
  )
);

effectName$ = createEffect(() => this.actions$.pipe(
  ofType(FeatureActions.action),
  operator(() =>
    apiSource.pipe(
      map(data => FeatureActions.actionSuccess({ data })),
      catchError(error => of(FeatureActions.actionFailure({ error }))))
    )
  )
);
```

Notice the actions and action are using the same replaceable values

**Comment by alex-okrushko** [comment]
Hi @johnpapa 
Are you talking about `${3:action}` and `$3Success` / `$3Failure`? Probably shouldn't be the same, but they could be.

In this CL I'm just adjusting the function, so it's wrapped with return statement, since it's a lot easier to debug it this way. (You can see the discussion this the linked issue).

**Comment by alex-okrushko** [comment]
@johnpapa anything else you'd like for me to address?

**Comment by johnpapa** [comment]
Sorry for the delay. 

All is well. Thanks for the PR.

**Pull request merged**
