### PR TITLE
Adding ng-container, ng-template and ng-content snippets

### PR DESCRIPTION
**Pull request by henriquecustodia**
## Purpose
* Adding snippets to use `ng-container`, `ng-template` and `ng-content` elements quickly.

## What
* Adding snippets to `html.json`

## How to Test
* type a-ng-container, then press tab 
   > To use ng-container element

* type a-ng-template, then press tab 
   > To use ng-template element

* type a-ng-content, then press tab 
   > To use ng-content element

## What to Check
Verify that the following are valid

* `a-ng-container` should print following html code
```html
   <ng-container ></ng-container>
```

* `a-ng-template` should print following html code
```html
   <ng-template [ngTemplateOutlet]="outlet" [ngOutletContext]="context"></ng-template>
```

* `a-ng-content` should print following html code
```html
   <ng-content select="selector"></ng-content>
```

### CODE REVIEW

**Comment by johnpapa** [comment]
thanks!

can you add these to the readme to please?

**Comment by henriquecustodia** [comment]
snippets were added to readme :+1:

**Comment by Xaviju** [comment]
This is so useful! I would love to see it in the editor. Will it be merged soon?
Thanks both for your work :heart:

**Review by johnpapa — APPROVED** [review]
thanks

**Pull request merged**
