### PR TITLE
Add NgRx Snippets

### PR DESCRIPTION
**Pull request by wesleygrimes**
## Purpose
* Resolves issue #93 

## What
* Added snippets for common NgRx commands including:
  - `createAction`
  - `createEffect`
  - `createReducer`
  - `createSelector`

## How to Test
* Open new `*.ts` file and type `a-ngrx-` and tab complete through the various newly added snippets.

## What to Check
Verify that the following are valid
* Confirm that the createEffect w/ API and createSelector w/ Props are outputting as desired. This is where we can get a little more opinionated, so I tried to stay agnostic.

## Other Notes
Thanks to @timdeschryver and his inspiration with the following gist: https://gist.github.com/timdeschryver/bad232582c01edd4aaffaee1ac9ccfc3

### CODE REVIEW

**Comment by johnpapa** [comment]
I don;t think we need the `scope` to be set as these are already in a typescript.json file. Please remove those, unless there is a reason I am missing? If so, we should update all snippets. Right?

Question - `a-ngrx-data-store-module` does it make sense anymore? SHould we instead have a snippet to create a ngrx module and another snippet(s) to add the pieces to it for ngrx/data ?

**Comment by wesleygrimes** [comment]
> create a ngrx module and another snippet(s) to add the pieces to it for ngrx/data ?

OK, I have removed `scope`, it was just a carryover. 

Regarding `a-ngrx-data-store-module`, what about the following:

- Remove `a-ngrx-data-store-module`
- Create `a-ngrx-store-module` which would scaffold a vanilla `StoreModule` with `EffectsModule` and `StoreDevtoolsModule`
- Create `a-ngrx-data-module-import` - This would be a one-liner with this `EntityDataModule.forRoot(entityConfig)`?

**Comment by johnpapa** [comment]
I like it. probably need v8.1.0 then for semantic versioning

**Comment by wesleygrimes** [comment]
OK Should be all set for your review, let me know what you think.

**Comment by johnpapa** [comment]
Merged and published in v8.1.0

thanks!

**Pull request merged**
