### PR TITLE
Snippet for Angular2 pipes.

### PR DESCRIPTION
**Pull request by joachimprinzbach**
Added snippet for simple ng2 pipes.

### CODE REVIEW

**Comment by mohammedzamakhan** [comment]
:+1:

**Comment by EmmanuelDemey** [comment]
The pipe should implements `PipeTransform`

**Comment by joachimprinzbach** [comment]
@Gillespie59  Thx for the hint - I don't know why it was missing in the API docs for custom pipes. It does work without implementing PipeTransform though...

**Comment by johnpapa** [comment]
i just reported to the docs.

the interface should be here.

**Pull request merged**
