### PR TITLE
Angular Resolver

### PR DESCRIPTION
**Pull request by ashinzekene**
## Purpose
* ability to use Angular resolver to fetch data before routing

## What
* [Angular Resolver](https://angular.io/guide/router#resolve-pre-fetching-component-data)
* [Resolver Docs](https://angular.io/api/router/Resolve)

## How to Test
* `a-resolver`

## What to Check
Verify that the following are valid
*  `a-resolver`

### CODE REVIEW

**Comment by johnpapa** [comment]
thanks!

can you add these to the readme to please?

**Comment by ashinzekene** [comment]
Done

**Comment by johnpapa** [comment]
thanks. i'll look at this in Dec ... been busy with event season. sorry for the delay

**Comment by johnpapa** [comment]
Please remove the comments in the snippet, fix whitespaces (it appears there are some extras), and update the merge conflicts and I think we can merge

**Comment by ashinzekene** [comment]
On it

**Comment by ashinzekene** [comment]
Can you please check this when you're free?

**Review by johnpapa — CHANGES_REQUESTED** [review]
Please add change log and up the minor version 

Also consider adding provided in root

**Comment by ashinzekene** [comment]
Done

**Pull request merged**
