### PR TITLE
Add more form snippets

### LINKED ISSUE #96: Feature Request - Angular Forms
I'd love to see a few snippets for quickly creating a form. A few useful ones would be

### `a-form`

```html
<form (ngSubmit)="onSubmit()" #myForm="ngForm">
</form>
```

### `a-form-submit`
```html
<button type="submit" [disabled]="!myForm.form.valid">
    Save
</button>
```

### PR DESCRIPTION
**Pull request by stefnotch**
## Purpose
* Fix #96

## What
* Adds a snippet to quickly create angular forms
* Adds a snippet to quickly create a submit button for angular forms

## How to Test
* Type `a-form` and `a-form-submit`

## What to Check
Verify that the following are valid
* The outputs of the `a-form` and `a-form-submit` snippets

### CODE REVIEW

**Comment by johnpapa** [comment]
this is in the incorrect file and should be in the html.json file, since it applies to html.

also, is this adding additional value in your opinion over the angular langauge service snippets?

**Comment by stefnotch** [comment]
@johnpapa I'm slightly confused here, since my snippet is in the `html.json` file. Is it possible that you intended to respond to a different PR?

**Comment by johnpapa** [comment]
yes, please forgive me.

I checked both a-form and a-form-submit and neither is working for me. here is what I see ...

**Comment by stefnotch** [comment]
I checked it out locally and it works for me. As you can see, `a-form` and `a-form-submit` do show up.

image

**Comment by johnpapa** [comment]
Can you try it in a file with an html extension? I wonder if there is something to that.

**Comment by stefnotch** [comment]
Yes of course.
I cloned my repository again, to make sure that there isn't some local change. Then I `npm install`ed everything and started it. It seems to work as expected on my end.
image

**Comment by johnpapa** [comment]
all set now

**Review by johnpapa — APPROVED** [review]

**Pull request merged**
